# ASM:=nasm
# # -I 指定依赖的头文件
# ASM_FLAGS:=-I boot/include/

# SOURCE_FILES:=$(wildcard *.asm)

# OBJ_FILES:=$(SOURCE_FILES:.asm=.bin)

# .PHONY: clean default

# default: ${OBJ_FILES}

# ${OBJ_FILES}: ${SOURCE_FILES} $(wildcard include/*.inc)
# 	${ASM} ${ASM_FLAGS} -o $@ $<

# clean:
# 	rm -rf *.bin